# Generated by Django 3.2.5 on 2021-07-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('apelido', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=9)),
                ('imail', models.EmailField(max_length=254)),
                ('dataNascimento', models.DateField()),
            ],
        ),
    ]
